2.3. GIẢI THUẬT 3: BAYES NGÂY THƠ (NAÏVE BAYES)

2.3.1. Ôn tập lý thuyết

1. Giải thuật Naive Bayes hoạt động như thế nào?
Naive Bayes là một thuật toán phân loại dựa trên định lý Bayes với một giả định "ngây thơ" (naive) về tính độc lập của các đặc trưng. Về cơ bản, thuật toán tính xác suất một điểm dữ liệu thuộc về một lớp cụ thể, sau đó gán nó vào lớp có xác suất cao nhất.

Định lý Bayes
Định lý Bayes mô tả xác suất của một sự kiện, dựa trên kiến thức có trước về các điều kiện có thể liên quan đến sự kiện đó. Công thức như sau:

P(A | B) = [P(B | A) * P(A)] / P(B)

Trong ngữ cảnh phân loại:

y: là lớp (ví dụ: "Spam" hoặc "Không phải Spam").
X: là một tập hợp các đặc trưng (ví dụ: các từ trong email). X = (x₁, x₂, ..., xₙ).
Công thức được viết lại là:

P(y | X) = [P(X | y) * P(y)] / P(X)

Trong đó:

P(y | X) (Xác suất hậu nghiệm - Posterior Probability): Xác suất để đối tượng thuộc lớp y khi biết các đặc trưng X. Đây là thứ chúng ta muốn tìm.
P(X | y) (Xác suất có điều kiện - Likelihood): Xác suất xuất hiện các đặc trưng X nếu biết đối tượng thuộc lớp y.
P(y) (Xác suất tiên nghiệm - Prior Probability): Xác suất của lớp y trong tập dữ liệu.
P(X) (Xác suất của bằng chứng - Evidence): Xác suất xuất hiện của các đặc trưng X.
Mục tiêu của thuật toán là tìm lớp y sao cho P(y | X) là lớn nhất. Vì P(X) là hằng số đối với tất cả các lớp, ta có thể bỏ qua nó và chỉ cần so sánh P(X | y) * P(y).

Giả định "Ngây thơ" (Naive Assumption)
Đây là bước làm cho thuật toán trở nên "ngây thơ". Naive Bayes giả định rằng tất cả các đặc trưng x₁, x₂, ..., xₙ là độc lập với nhau khi biết lớp y.

Điều này có nghĩa là sự xuất hiện của một đặc trưng không ảnh hưởng đến sự xuất hiện của đặc trưng khác. Ví dụ, khi phân loại email, thuật toán giả định rằng sự xuất hiện của từ "miễn phí" không liên quan đến sự xuất hiện của từ "khuyến mãi", mặc dù trong thực tế chúng thường đi cùng nhau.

Nhờ giả định này, việc tính toán P(X | y) trở nên cực kỳ đơn giản: P(X | y) = P(x₁ | y) * P(x₂ | y) * ... * P(xₙ | y)

Thay vì phải tính một xác suất kết hợp phức tạp, ta chỉ cần tính xác suất của từng đặc trưng riêng lẻ rồi nhân chúng lại với nhau.

2. Các loại mô hình Naive Bayes và khi nào nên sử dụng
Có ba loại mô hình Naive Bayes chính, được phân biệt bởi giả định về phân phối của dữ liệu:

Loại mô hình	Đặc điểm dữ liệu	Giả định	Ví dụ sử dụng
Gaussian Naive Bayes	Đặc trưng là liên tục (số thực).	Giả định rằng giá trị của mỗi đặc trưng tuân theo phân phối chuẩn (Gaussian).	- Phân loại dựa trên chiều cao, cân nặng, nhiệt độ.- Dự đoán điểm tín dụng dựa trên thu nhập, tuổi.
Multinomial Naive Bayes	Đặc trưng là rời rạc, thường là số đếm hoặc tần suất.	Giả định rằng các đặc trưng tuân theo phân phối đa thức (Multinomial).	- Phân loại văn bản: đặc trưng là số lần xuất hiện của một từ trong văn bản (Bag-of-Words, TF-IDF).- Phân loại chủ đề tin tức.
Bernoulli Naive Bayes	Đặc trưng là nhị phân (binary/boolean), tức là chỉ có giá trị 0 hoặc 1.	Giả định rằng các đặc trưng tuân theo phân phối Bernoulli.	- Phân loại văn bản: đặc trưng là sự hiện diện (1) hay vắng mặt (0) của một từ trong văn bản, không quan tâm đến số lần xuất hiện.- Phân tích cảm xúc (sentiment analysis) dựa trên việc một từ khóa tích cực/tiêu cực có xuất hiện hay không.

3. Tại sao Naive Bayes được gọi là "ngây thơ"?
Thuật toán này được gọi là "ngây thơ" (naive) chính vì giả định về tính độc lập của các đặc trưng.

Trong thực tế, giả định này hầu như luôn sai. Các đặc trưng thường có mối liên hệ với nhau. Ví dụ:

Trong phân loại văn bản, các từ "New" và "York" có khả năng xuất hiện cùng nhau rất cao.
Trong chẩn đoán y tế, các triệu chứng như "sốt" và "ho" thường liên quan đến nhau.
Ảnh hưởng đến hiệu suất:

Mặt tích cực: Giả định này giúp đơn giản hóa việc tính toán một cách đáng kể. Thay vì tính toán một ma trận hiệp phương sai phức tạp, ta chỉ cần tính xác suất riêng lẻ của từng đặc trưng. Điều này làm cho Naive Bayes:
Rất nhanh để huấn luyện và dự đoán.
Hoạt động tốt với dữ liệu có số chiều lớn (nhiều đặc trưng), ví dụ như trong phân loại văn bản với hàng nghìn từ.
Yêu cầu ít dữ liệu huấn luyện hơn so với các mô hình phức tạp khác.
Mặt tiêu cực: Vì giả định này không đúng với thực tế, xác suất hậu nghiệm P(y | X) mà mô hình tính ra thường không chính xác. Tuy nhiên, điều đáng ngạc nhiên là Naive Bayes vẫn thường cho kết quả phân loại tốt. Lý do là nó không cần tính ra xác suất chính xác, mà chỉ cần xác định được lớp nào có xác suất cao hơn các lớp khác.

4. Ưu điểm và hạn chế của Naive Bayes
Ưu điểm	Hạn chế
Nhanh và hiệu quả: Tốc độ huấn luyện và dự đoán rất nhanh.	Giả định độc lập "ngây thơ": Giả định này hiếm khi đúng trong thực tế, có thể làm giảm độ chính xác nếu các đặc trưng phụ thuộc mạnh vào nhau.
Yêu cầu ít dữ liệu: Hoạt động tương đối tốt ngay cả với tập dữ liệu nhỏ.	Vấn đề xác suất bằng 0 (Zero-Frequency Problem): Nếu một đặc trưng chưa từng xuất hiện cùng một lớp trong tập huấn luyện, xác suất của nó sẽ bằng 0, làm cho toàn bộ xác suất hậu nghiệm của lớp đó bằng 0. (Có thể khắc phục bằng kỹ thuật Laplace Smoothing).
Hoạt động tốt với dữ liệu nhiều chiều: Rất phù hợp cho các bài toán có số lượng đặc trưng lớn như phân loại văn bản.	Khó biểu diễn mối quan hệ phức tạp: Không thể nắm bắt được sự tương tác giữa các đặc trưng, không hiệu quả bằng SVM hay Random Forest trên các tập dữ liệu có cấu trúc phức tạp.
Dễ triển khai và diễn giải: Logic của thuật toán khá đơn giản.	Hiệu suất kém với dữ liệu liên tục: Gaussian NB giả định dữ liệu tuân theo phân phối chuẩn, nếu không đúng thì kết quả sẽ kém.
So với SVM hoặc Random Forest:

Naive Bayes nhanh hơn, đơn giản hơn và phù hợp cho các bài toán cơ bản, đặc biệt là phân loại văn bản.
SVM và Random Forest thường cho độ chính xác cao hơn trên các tập dữ liệu phức tạp vì chúng có thể mô hình hóa các mối quan hệ phi tuyến và tương tác giữa các đặc trưng. Tuy nhiên, chúng đòi hỏi nhiều tài nguyên tính toán và dữ liệu hơn.

5. Code mẫu xây dựng mô hình Gaussian Naive Bayes
Dưới đây là đoạn code Python sử dụng thư viện Scikit-learn để xây dựng một mô hình Gaussian Naive Bayes đơn giản.

In [1]:
# Bước 1: Import các thư viện cần thiết
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import datasets
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Bước 2: Tải và chuẩn bị dữ liệu
# Sử dụng bộ dữ liệu Iris nổi tiếng làm ví dụ
# Dữ liệu gồm 4 đặc trưng (liên tục) và 3 lớp hoa
iris = datasets.load_iris()
X = iris.data  # Đặc trưng (features)
y = iris.target # Nhãn (labels)

# In ra để xem qua dữ liệu
print("Số lượng mẫu dữ liệu:", X.shape[0])
print("Số lượng đặc trưng:", X.shape[1])
print("Các lớp:", np.unique(y))

# Bước 3: Chia dữ liệu thành tập huấn luyện (train) và tập kiểm tra (test)
# 80% cho huấn luyện, 20% cho kiểm tra
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("\nKích thước tập huấn luyện:", X_train.shape)
print("Kích thước tập kiểm tra:", X_test.shape)

# Bước 4: Xây dựng và huấn luyện mô hình Gaussian Naive Bayes
# Khởi tạo mô hình
model = GaussianNB()

# Huấn luyện mô hình trên tập train
model.fit(X_train, y_train)
print("\nĐã huấn luyện xong mô hình Gaussian Naive Bayes!")

# Bước 5: Đánh giá hiệu suất của mô hình
# Dự đoán nhãn cho tập test
y_pred = model.predict(X_test)

# Tính toán độ chính xác
accuracy = accuracy_score(y_test, y_pred)
print(f"\nĐộ chính xác của mô hình: {accuracy:.2f}")

# In ra các chỉ số đánh giá khác
print("\nBáo cáo phân loại (Classification Report):")
print(classification_report(y_test, y_pred, target_names=iris.target_names))

print("\nMa trận nhầm lẫn (Confusion Matrix):")
print(confusion_matrix(y_test, y_pred))

# Bước 6: Sử dụng mô hình để dự đoán cho dữ liệu mới
# Ví dụ một bông hoa mới có các số đo [5.1, 3.5, 1.4, 0.2]
new_flower = np.array([[5.1, 3.5, 1.4, 0.2]])
prediction = model.predict(new_flower)
predicted_class_name = iris.target_names[prediction[0]]

print(f"\nDự đoán cho mẫu mới {new_flower}: Lớp '{predicted_class_name}'")


Số lượng mẫu dữ liệu: 150
Số lượng đặc trưng: 4
Các lớp: [0 1 2]

Kích thước tập huấn luyện: (120, 4)
Kích thước tập kiểm tra: (30, 4)

Đã huấn luyện xong mô hình Gaussian Naive Bayes!

Độ chính xác của mô hình: 1.00

Báo cáo phân loại (Classification Report):
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Ma trận nhầm lẫn (Confusion Matrix):
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

Dự đoán cho mẫu mới [[5.1 3.5 1.4 0.2]]: Lớp 'setosa'


6. Xử lý dữ liệu phân loại (Categorical Data) cho Multinomial Naive Bayes
Multinomial Naive Bayes yêu cầu đầu vào là các giá trị số (thường là số đếm). Do đó, dữ liệu dạng chuỗi (categorical) cần được chuyển đổi. Hai phương pháp phổ biến là:

One-Hot Encoding: Biến mỗi giá trị của một cột categorical thành một cột nhị phân mới. Cách này không phù hợp với Multinomial NB vì nó tạo ra các đặc trưng nhị phân (phù hợp hơn với Bernoulli NB) và làm tăng số chiều dữ liệu.

Count Vectorizing (Bag-of-Words): Đây là phương pháp chính được sử dụng, đặc biệt trong phân loại văn bản.

Tạo từ điển: Xây dựng một từ điển chứa tất cả các từ (token) duy nhất trong toàn bộ văn bản.
Vector hóa: Biến mỗi văn bản thành một vector số. Mỗi phần tử trong vector tương ứng với một từ trong từ điển và giá trị của nó là số lần từ đó xuất hiện trong văn bản.
Thư viện Scikit-learn cung cấp CountVectorizer để thực hiện việc này một cách dễ dàng.

7. Triển khai Naive Bayes cho phân loại văn bản
Đây là ứng dụng kinh điển và rất hiệu quả của Naive Bayes (thường là Multinomial hoặc Bernoulli).

Quy trình thực hiện:

Thu thập và tiền xử lý dữ liệu:

Thu thập các văn bản và nhãn tương ứng (ví dụ: email và nhãn "spam"/"ham").
Làm sạch văn bản: Chuyển thành chữ thường, loại bỏ dấu câu, số, và các từ dừng (stop words) như "và", "là", "của",...
Trích xuất đặc trưng (Feature Extraction):

Sử dụng CountVectorizer (cho Multinomial NB) hoặc TfidfVectorizer từ Scikit-learn để biến các văn bản đã làm sạch thành các vector số.
CountVectorizer: Đếm tần suất xuất hiện của từ (Bag-of-Words).
TfidfVectorizer: Tính trọng số TF-IDF (Term Frequency-Inverse Document Frequency), giúp giảm trọng số của các từ phổ biến và tăng trọng số của các từ quan trọng, đặc trưng cho văn bản.
Chia dữ liệu: Chia tập dữ liệu đã vector hóa thành tập huấn luyện và tập kiểm tra.

Huấn luyện mô hình:

Khởi tạo mô hình MultinomialNB.
Huấn luyện mô hình trên tập huấn luyện. Một điểm quan trọng của MultinomialNB là tham số alpha (mặc định là 1.0), dùng cho kỹ thuật Laplace/Lidstone smoothing để giải quyết vấn đề xác suất bằng 0.
Đánh giá mô hình:

Dùng mô hình đã huấn luyện để dự đoán trên tập kiểm tra.
Đánh giá hiệu suất bằng các chỉ số như accuracy, precision, recall, F1-score.
Sử dụng: Dùng mô hình để phân loại các văn bản mới.

Hy vọng những giải thích trên sẽ giúp bạn hiểu rõ hơn về thuật toán Naive Bayes!

Nhiệm vụ 1: Phân loại sử dụng Naïve Bays
1. Import thư viện và nạp dữ liệu vào notebook

In [21]:
#Importing the Necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report
data = pd.read_csv('spam.csv', encoding='latin-1')
#display the first 5 rows
data.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

2. Xử lý dữ liệu trước khi xây dựng mô hình từ dữ liệu

In [11]:
# Drop the columns with NaN values
data = data.drop(columns=['Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4'],axis=1,errors='ignore')
# Rename columns for clarity:
data.columns = ['label', 'text']
# Separate features (X) and target labels (y)
X = data.drop('label', axis=1)
y = data['label']
# Split the data into training and testing sets (80% training, 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

3. Xây dựng vector hóa nội dung HAM | SPAM của tập train và tập test

In [ ]:
import pandas as pd
data = pd.read_csv(".csv", encoding='utf-8')

# Giữ đúng cột text
data = data[['label', 'message']]
data.columns = ['label', 'text']
data['text'] = data['text'].fillna('').astype(str)


4. Xây dựng mô hình Naïve Bayes

In [ ]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train_vectorized, y_train)

5. Đánh giá hiệu quả của mô hình

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix,
classification_report
# Make predictions on the test data
y_pred = classifier.predict(X_test_vectorized)
# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
classification_rep = classification_report(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")
print("Confusion Matrix:")
print(conf_matrix)
print("Classification Report:")
print(classification_rep)